# status(min/max)

In [1]:
import numpy as np

In [5]:
a=np.random.rand(10)


In [6]:
print a

[0.44625667 0.48191964 0.55539402 0.62797886 0.85389088 0.54847388
 0.49147384 0.12527716 0.85909585 0.52089463]


In [7]:
print np.min(a)

0.1252771554574028


In [8]:
print np.max(a)

0.8590958454118852


In [9]:
a=np.random.rand(2,2)

In [10]:
print a

[[0.90858653 0.79573434]
 [0.15830052 0.94143625]]


In [11]:
print np.min(a,axis=0)

[0.15830052 0.79573434]


In [12]:
print np.min (a,axis=1)

[0.79573434 0.15830052]


In [13]:
a=np.random.rand(3,3)
print a
print np.max(a,axis=0)
print np.max(a,axis=1)

[[0.19688338 0.14240911 0.58546056]
 [0.50694013 0.36938851 0.70728498]
 [0.64924292 0.32359728 0.13669894]]
[0.64924292 0.36938851 0.70728498]
[0.58546056 0.70728498 0.64924292]


In [18]:
a=np. array([[1,4,10],[2,6,8]])


In [21]:
print np.median(a,axis=0)

[1.5 5.  9. ]


In [22]:
print np.median(a,axis=1)

[4. 6.]


In [26]:
from scipy import stats

In [27]:
a=np.array ([1,2,2,4,5,7,7])

In [28]:
print stats.mode(a)

ModeResult(mode=array([2]), count=array([2]))


# stats(variance/std)

In [29]:
a=np.array([1,3,5])

In [30]:
print np.mean(a)

3.0


In [31]:
print np.var(a)

2.6666666666666665


In [37]:
print np.std(a)

1.632993161855452


In [33]:
b=np.array([3,3,3])

In [34]:
print np.mean(b)

3.0


In [35]:
print np.std(b)

0.0


In [36]:
print np.var(b)

0.0
