In [1]:
import numpy as np 

In [4]:
a=np.array([1,2,3])        # vetor of 3 columns
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<type 'numpy.ndarray'>
(3,)


In [26]:
a=np.array([1,2,3])      # addition operation
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0 0 0]
[  1  32 729]


In [10]:
l1=[1,2,3]
l2=[4,5,6]
print(l1+l2)
l1=np.array(l1)
l2=np.array(l2)
print(l1+l2)
l1=l1.tolist()
print(type(l1))

[1, 2, 3, 4, 5, 6]
[5 7 9]
<type 'list'>


In [12]:
mat=np.array([[1,2,3],(4,5,6),[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
mat[0]

array([1, 2, 3])

In [15]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(mat.T)  #transpose of a matrix

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
print(2*mat)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [20]:
print(mat[:,1])

[2 5 8]


# indentity matrix

In [21]:
indentity=np.eye(3)
print(indentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
onesmatrix= np.ones([3])
print(onesmatrix)
zeromatrix=np.zeros([3,3])
print(zeromatrix)

[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
random_matrix = np.random.rand(10,10)
print(random_matrix.shape)
print(random_matrix)

(10, 10)
[[0.81686722 0.91945922 0.32128461 0.03346948 0.17724472 0.55508658
  0.4919789  0.97033646 0.56988659 0.08554458]
 [0.91090885 0.38045703 0.98129638 0.58928964 0.69774169 0.16970493
  0.41854282 0.81483523 0.36865848 0.32746577]
 [0.88046835 0.03754159 0.48455978 0.97058878 0.16523687 0.75505095
  0.77710018 0.67558979 0.40155355 0.810101  ]
 [0.24274907 0.24848891 0.30608023 0.64308221 0.24329967 0.40164954
  0.10949565 0.92534505 0.74348277 0.59627483]
 [0.0293247  0.10061455 0.46188209 0.3269591  0.35069098 0.74032195
  0.17850845 0.48081363 0.99474679 0.11921846]
 [0.12577738 0.21944758 0.14084133 0.9646469  0.90990638 0.80311439
  0.54648166 0.49260885 0.07188328 0.5101677 ]
 [0.14208109 0.91640577 0.95936523 0.25248358 0.428626   0.25817455
  0.69094957 0.04479503 0.07283788 0.58436962]
 [0.34559454 0.35795064 0.58708046 0.22830438 0.55870743 0.04852789
  0.19558497 0.1994358  0.68061078 0.51344904]
 [0.60675288 0.47354825 0.4826173  0.87989972 0.67544988 0.96864346
  0

In [22]:
def arthimatic_operations(x,y):
    addition    = x+y
    subtraction = x-y
    mul         = x*y
    div         = x/y
    return addition,subtraction,mul,div

In [23]:
a,s,m,d = arthimatic_operations (3,4)

In [24]:
print (a,s,m,d,)

(7, -1, 12, 0)


In [25]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
def vector_operations(x,y):
    additon = x+y
    subtraction = x-y
    mul = x*y
    div = x/y
    return addition,subtraction,mul,div

a,s,m,d = vector_ operation (x,y)

In [26]:
print(a,s,m,d)

(7, -1, 12, 0)


In [42]:
import operations

In [43]:
print(operations.arthimatic_operations(4,5))

(9, -1, 20, 0)


In [49]:
# specify the array range 
a = np.arange(100)
print a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [50]:
# reshape the array
a = np.reshape(a,(10,10))
print a

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [59]:
a=np.random.rand(10)

In [60]:
a=np.random.rand(10,10)
print (a)

[[0.67245797 0.99311145 0.57106305 0.85091993 0.72833399 0.85962771
  0.3108222  0.23960952 0.60875577 0.44569452]
 [0.80616962 0.99470442 0.10800661 0.88990771 0.35692148 0.63417089
  0.96476358 0.52396621 0.24616809 0.58371741]
 [0.79327157 0.573363   0.84279029 0.00723516 0.36736974 0.88963837
  0.32656312 0.47197198 0.56137227 0.10225227]
 [0.14737038 0.26276274 0.96696058 0.5341069  0.10821524 0.27737509
  0.55924873 0.70515866 0.68335426 0.97059007]
 [0.78833949 0.37856872 0.57841418 0.98110256 0.81464487 0.22455465
  0.43317722 0.14057876 0.33136763 0.19585051]
 [0.45058985 0.58409364 0.1074399  0.98865997 0.86881278 0.23604395
  0.68943126 0.52464095 0.59792669 0.08071461]
 [0.72487883 0.05969278 0.6216936  0.46661469 0.87417882 0.13128259
  0.69535387 0.93541386 0.83035466 0.38438054]
 [0.39917241 0.0625732  0.06052862 0.59314092 0.64609737 0.91567097
  0.36587421 0.08787526 0.57084895 0.26773697]
 [0.75981244 0.32521959 0.48958923 0.04538627 0.84852773 0.23253103
  0.11446163

In [63]:
 import numpy as np
    #flatten the array
 a=np.random.rand(10)
 print (np.ravel(a))

[0.92216532 0.84027908 0.15031594 0.66444425 0.78337823 0.2503529
 0.23403074 0.08865131 0.55385957 0.28982374]


In [64]:
#apply logirthm on array a
print np.log(a)

[-0.08103077 -0.17402121 -1.89501591 -0.4088043  -0.24413965 -1.38488374
 -1.45230283 -2.42304447 -0.59084411 -1.23848233]


In [65]:
#find the eigen values of a matrix
a= np.arange(4).reshape(2,2)
print a 
values,vectors = np.linalg.eig(a)
print "eigen values are",values
print "eigen vectors are",vectors

[[0 1]
 [2 3]]
eigen values are [-0.56155281  3.56155281]
eigen vectors are [[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


In [66]:
#determinant of a matrix
print np.linalg.det(a)

-2.0


In [67]:
#matrix power of 4
print np.linalg.matrix_power (a,4)

[[ 22  39]
 [ 78 139]]


# mean of vector

In [68]:
import numpy as np
a= np.array ([1,2,3])

In [69]:
print np.mean(a)

2.0


In [70]:
a=np.array([[1,2,3],[4,5,6]])
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[2.5 3.5 4.5]
[2. 5.]


# dictionaries

In [75]:
d = {'cat':'cute','dog':'furry'}      #create a new dictionary
print (d['cat'] )                      
print  (d.keys())
print(d.values())
print(d.items())
for key,values in d.items():
    print(key,values)
    
    

cute
['dog', 'cat']
['furry', 'cute']
[('dog', 'furry'), ('cat', 'cute')]
('dog', 'furry')
('cat', 'cute')


In [78]:
print(d.get('cat'))
print(d.get('hello'))
print(len(d))

cute
None
2
