## Numpy Intro

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3]) 

In [4]:
a1 = np.array([1, 2, 'Hello']) 

In [6]:
a

array([1, 2, 3])

In [5]:
a1

array(['1', '2', 'Hello'],
      dtype='<U11')

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.shape)

(3,)


In [9]:
a.dtype

dtype('int32')

In [10]:
a1.dtype

dtype('<U11')

In [11]:
a[0]

1

In [11]:
a1[2]

'Hello'

In [12]:
b = np.array([[1,2,3],[4,5,6]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(b.shape)

(2, 3)


In [16]:
b[0,1],b[0,0]

(2, 1)

In [14]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [15]:
x = np.ones((2,2))  # Create an array of all ones
print(x)

[[ 1.  1.]
 [ 1.  1.]]


In [16]:
x = np.full((2,2),7)  # Create an array of all ones
print(x)

[[7 7]
 [7 7]]


In [27]:
np.random.seed(123)

In [28]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[ 0.69646919  0.28613933]
 [ 0.22685145  0.55131477]]


In [29]:
x =[2,4,5,2,10,1]
np.random.shuffle(x)
print(x)

[10, 2, 4, 1, 5, 2]


In [57]:
np.random.seed(132)

In [58]:
np.random.choice(x,2)

array([2, 4])

In [59]:
a = np.array([[1,2,3], [3, 4,5], [5, 6,7]])
b = a[:2, 1:3]


In [61]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [62]:
print(b)

[[2 3]
 [4 5]]


In [63]:
b[0,0]=22

In [64]:
b

array([[22,  3],
       [ 4,  5]])

In [21]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a 
print(row_r1,row_r1.shape )
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r2,row_r2.shape )
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r3,row_r3.shape )

[3 4 5] (3,)
[[3 4 5]] (1, 3)
[[3 4 5]] (1, 3)


In [24]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
p = np.array([1, 2], dtype=np.str)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype,p.dtype)

int32 float64 int64 <U1


## Numpy Math

In [65]:
x = np.array([1,2,3])
y = np.array([10,20,30])

In [27]:
np.multiply(x,y)

array([10, 40, 90])

In [28]:
np.divide(x,y)

array([ 0.1,  0.1,  0.1])

In [30]:
np.add(x,y)

array([11, 22, 33])

In [31]:
np.subtract(x,y)

array([ -9, -18, -27])

In [32]:
np.dot(x,y)

140

In [33]:
x.dot(y)

140

In [74]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,7,10],[8,9,1],[10,11,1]])

In [75]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
y

array([[ 6,  7, 10],
       [ 8,  9,  1],
       [10, 11,  1]])

In [77]:
np.matmul(x,y)

array([[ 52,  58,  15],
       [124, 139,  51]])

In [78]:
np.matmul(y,x)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)